application: chrome-devtools-frontend
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static/\d+\.\d+\.\d+\.\d+/Images
  static_dir: static/Images

- url: /static
  static_dir: static

- url: .*
  script: main.py
